# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build PDF with FOP and PDF/UA-1 mode active
      run: mvn exec:java -Dexec.mainClass="org.apache.fop.cli.Main" -Dexec.args="-c config/fop-config-ua.xml -fo table.fo -pdf out/table-ua.pdf"
    - name: Build PDF with FOP and PDF/UA-1 mode inactive
      run: mvn exec:java -Dexec.mainClass="org.apache.fop.cli.Main" -Dexec.args="-c config/fop-config.xml -fo table.fo -pdf out/table.pdf"
    - name: Build PDF 1.4 with FOP
      run: mvn exec:java -Dexec.mainClass="org.apache.fop.cli.Main" -Dexec.args="-c config/fop-config14.xml -fo table.fo -pdf out/table14.pdf"